### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by pavittarx**
few fixes, & a ReadMe update with direct link to download & installation instructions.

### CODE REVIEW

**Comment by pavittarx** [comment]
@FabianLauer I did as you said, but now what with this pull request?

**Comment by bastienlemaitre** [comment]
@FabianLauer, any new ?

**Comment by FabianLauer** [comment]
@pavittarx I think we had a bit of a misunderstanding regarding https://github.com/FabianLauer/chrome-vs-code/pull/6#issuecomment-393840875 🙂

What I meant was: Can you please open a PR in which you add the link to the VSIX, without _any_ other changes? Thanks! 🙂

**Comment by pavittarx** [comment]
@FabianLauer well, I guess, I took it the other way, would you mind me opening a new PR?

**Comment by FabianLauer** [comment]
Not at all, go for it 👍

**Pull request closed without merging**
